# Generated by Django 2.2.6 on 2019-11-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mems', '0002_mempost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mempost',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='mempost',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='mempost',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Ссылка на mem'),
        ),
        migrations.AlterField(
            model_name='mempost',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название mem'),
        ),
    ]
